### ISSUE TITLE
User Account: Add `authclient`, `authclient_id`.

### ISSUE THREAD

**Issue by luke-** [humhub/rest#106]
- It should be possible to specify the following optional `account` fields when creating a user: 

- `authclient` referes to `user.auth_mode` 
- `authclient_id` referes to `user.authclient_id`.
 
https://github.com/humhub/rest/blob/master/definitions/UserDefinitions.php#L51

These are also to be returned.

- In addition to `/user/get-by-username`, there should also be a `/user/get-by-authclient`. 

This should find the user by the parameters `name` of the authclient (`user.auth_mode`) and `id` value of `user.authclient_id`.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/rest/pull/111: Please note on previous version the core scenario `User::SCENARIO_EDIT_ADMIN` was used from REST API side for add and update user, in order to don't touch the core scenario I decided to extend the model `User` from REST module side with new model `ApiUser`.
If you don't like such wrapper/extenssion please let me know, and otherwise we should modify a core side in order to either add fields into the existing scenario or create new one with name like `SCENARIO_API_REQUEST = 'apiRequest`, but I am not sure it is a good idea to mix a code from module with core code.

**Comment by luke-** [comment]
@yurabakhtin Thanks, the Wrapper Solution is good in this case.
