### ISSUE TITLE
Wrong `contentcontainer` table record for created users

### ISSUE THREAD

**Issue by luke-** [humhub/rest#129]
When a user is created via the REST API, the corresponding entry in the `contentcontainer` table is invalid. 

e.g.

```
*************************** 87. row ***************************
           id: 92
         guid: 161add5c-d307-4eaa-936a-b89c12698882
        class: humhub\modules\rest\models\ApiUser
           pk: 43
owner_user_id: 43
  tags_cached: NULL
*************************** 88. row ***************************
           id: 93
         guid: a37e5beb-8545-41f8-968c-5e5b89d06291
        class: humhub\modules\rest\models\ApiUser
           pk: 44
owner_user_id: 44
  tags_cached: NULL
```

This should be also checked for Spaces.

Basically, we should not extend the user object or only in exceptional cases. Maybe even a marking as `final` would be good.

**Comment by yurabakhtin** [comment]
@luke- 

> Basically, we should not extend the user object or only in exceptional cases. Maybe even a marking as `final` would be good.

I don't think we cam apply `final` now, because I see the `User` is extended for 10+ classes and `Space` - for 5.
I decided to apply the solution - https://github.com/humhub/humhub/pull/6388

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/rest/pull/130 - to avoid extension of the core `User`.
Could you please review it and correct me if you mean some other solution, because I could not apply your solution `$user->validators->append([['authclient_id'], 'string', 'max' => 60]);`, so I created the `ApiUser` as wrapper model for the core `User`.
