### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by luke-** [humhub/rest#53]

**Comment by yurabakhtin** [comment]
@luke- I have started this in PR https://github.com/humhub/rest/pull/59, only for module `auth` yet.

**Comment by luke-** [comment]
@yurabakhtin Looks good so far. Thanks for the update!

**Comment by yurabakhtin** [comment]
- User - Default Controller - https://github.com/humhub/rest/pull/59/commits/2609ddb10101eb445c06b269159823d6d19c6276

**Comment by luke-** [comment]
@yurabakhtin Thanks for the effort, looks good so far!

**Comment by yurabakhtin** [comment]
@luke- I have done all tests for this module `rest`. You can merge the PR https://github.com/humhub/rest/pull/59, also please merge core PR https://github.com/humhub/humhub/pull/5073.

**Comment by luke-** [comment]
Any idea? https://github.com/humhub/rest/runs/2620269086?check_suite_focus=true

**Comment by yurabakhtin** [comment]
@luke- The error `Error: ;1m  [Error] Class "humhub\modules\Activity\models\Activity" not found` looks strange because on my local server I could not reproduce the issue. I only guess the server cannot find the class by name `humhub\modules\Activity\models\Activity` and probably it needs an slash like this `\humhub\modules\Activity\models\Activity`. For my server it works with both cases and without slash and with slash, I tested on PHP8 as well.

In some modules I see the code like `public $modelClass = Model::class;` instead of out current case `public $modelClass = 'humhub\modules\Module\models\Model';` so I have done these changes in PR https://github.com/humhub/rest/pull/62, probably it will solve the issues, but it is strange because some modules still uses the string class name way and it works.

Ok, after the fix the first error was gone but I got another error https://github.com/humhub/rest/runs/2627786921?check_suite_focus=true#step:23:92 `[yii\base\InvalidConfigException] The directory does not exist:`. I could reproduce this only if I remove a record `module_id = 'rest'` from the DB table `module_enabled` manually. Again strange bug because the code worked well on other modules(wiki, tasks) which uses rest api tests.
I have found a solution, please merge a core PR https://github.com/humhub/humhub/pull/5078 firstly, and after this merging I hope the tests of this module will works without errors on the PR https://github.com/humhub/rest/pull/62.

**Comment by luke-** [comment]
@yurabakhtin Thanks, the tests seems to be fixed: https://github.com/humhub/rest/pull/62/checks?check_run_id=2628493039
