### ISSUE TITLE
Problem updating user and space tags.

### ISSUE THREAD

**Issue by avillaindesire** [humhub/rest#67]
According to the documentation, tags should be presented as a single comma delimited string. If I get a user or a space (e.g. /space/{id}), the tags come back as an array of strings. Trying to update the tags of a user or a space, either with a string or an array of strings, doesn't seem to work. Is updating tags broken or is the documentation incorrect?

**Comment by luke-** [comment]
Tags were recently reworked and therefore probably cause problems.
@yurabakhtin Can you take a look into this?

**Comment by yurabakhtin** [comment]
@luke- Yes, the doc was wrong, I fixed it in PR https://github.com/humhub/rest/pull/68, probably we should allow to use `tags` instead of from `tagsField` at least from REST module side, let me know if I should to find a solution.
Also Space tags were not updated from REST API side, I fixed in core PR https://github.com/humhub/humhub/pull/5327.

**Comment by luke-** [comment]
@yurabakhtin Thank you for the quick fix.

I think the `tagsField` will work for now, but I have created an issue here for the future.

**Comment by yurabakhtin** [comment]
@avillaindesire Yes, the response still has the field `tags`, but in request we should use new `tagsField`. We just updated the doc pages to mark these fields as array instead of previous string format.
In next fix https://github.com/humhub/rest/issues/69 we will make to use also `tags` from request side.
