### ISSUE TITLE
Getting CORS blocked when requesting from localhost

### ISSUE THREAD

**Issue by arximughal** [humhub/rest#93]
We have a test HumHub instance installed on the free hosting while we are working on a react application to access the REST APIs. The problem is that when we try to access any resource from `http://localhost`, we get CORS blocked error. 

Is there any way we can make it work? We need to access the HumHub REST APIs from a different domain (atleast) during the development period of the project (i.e., http://localhost etc.).

**Comment by luke-** [comment]
Can you please post the exact error message? Do you have any CORS headers enabled? Usually there should be no default CORS headers in HumHub

**Comment by ArchBlood** [comment]
@luke- can this be reopened?
```
Access to fetch at 'https://example.com/api/v1/notification' from origin 'chrome-extension://xxxxxxxxxxxxxxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Basically what I try to do is fetch `/api/v1/notification` using API token inside of our chrome extension, this works very well for some time but after awhile the API token becomes invalid and blocked because CORS policy isn't set anywhere within the module, and I'd prefer not having to set `no-cors` on our end as it is more to do with the Rest API module's side of things.
